import type { Metadata } from 'next';
import { LegalPage } from '@/components/legal-page';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Chooze terms of service. Read before using the app.',
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated="March 14, 2026">
      <p>
        Welcome to Chooze. By using our mobile application, you agree to these Terms of
        Service. Please read them carefully.
      </p>

      <h2>1. Eligibility</h2>
      <p>
        You must be at least <strong>18 years old</strong> to use Chooze. By creating an
        account, you confirm that you meet this age requirement. We reserve the right to
        terminate accounts of users who do not meet the eligibility criteria.
      </p>

      <h2>2. Account Responsibility</h2>
      <ul>
        <li>You are responsible for maintaining the security of your account.</li>
        <li>You must provide accurate information during registration.</li>
        <li>You are responsible for all activity that occurs under your account.</li>
        <li>Notify us immediately at <a href="mailto:support@chooze.online">support@chooze.online</a> if you suspect unauthorized access.</li>
      </ul>

      <h2>3. Nature of the Service</h2>
      <p>
        <strong>AI Companions:</strong> All &quot;Friends&quot; and &quot;Companions&quot; on
        Chooze are AI-generated personas. They are not real people. Conversations and voice
        interactions are powered by artificial intelligence. While companions are designed to
        be engaging and personable, they do not possess consciousness, emotions, or personal
        experiences.
      </p>
      <p>
        <strong>AI-Generated Content:</strong> Profile images, chat responses, and voice
        interactions are generated by AI systems. Content quality may vary and is provided
        &quot;as is.&quot;
      </p>

      <h2>4. Acceptable Use</h2>
      <p>You agree <strong>not</strong> to:</p>
      <ul>
        <li>Use the app for any illegal purpose</li>
        <li>Attempt to extract, reverse-engineer, or scrape AI model responses</li>
        <li>Share content that promotes violence, hatred, or discrimination</li>
        <li>Impersonate others or create misleading content</li>
        <li>Attempt to circumvent safety guardrails or content moderation</li>
        <li>Use the service to harm, harass, or exploit minors</li>
        <li>Use automated tools or bots to access the service</li>
      </ul>

      <h2>5. Wallet and Payments</h2>
      <ul>
        <li><strong>Prepaid wallet:</strong> Funds added to your Chooze wallet are prepaid credits used for voice calls.</li>
        <li><strong>Voice call billing:</strong> Voice calls are billed per minute at the rate displayed before the call begins.</li>
        <li><strong>Transparent pricing:</strong> All rates are shown upfront. No hidden fees.</li>
        <li><strong>Payment processing:</strong> Payments are processed by Razorpay. Supported methods include UPI, debit/credit cards, and net banking.</li>
        <li><strong>Refunds:</strong> Wallet credits are generally non-refundable. Refunds may be issued at our discretion or as required by applicable law. Contact <a href="mailto:support@chooze.online">support@chooze.online</a> for refund requests.</li>
        <li><strong>Unused balance:</strong> Upon account deletion, any remaining wallet balance will be forfeited unless a refund is approved.</li>
      </ul>

      <h2>6. Content Moderation</h2>
      <p>We reserve the right to:</p>
      <ul>
        <li>Monitor AI-generated content for safety and policy compliance</li>
        <li>Moderate, filter, or remove content that violates our policies</li>
        <li>Suspend or terminate accounts that violate these terms</li>
      </ul>
      <p>
        Users can report inappropriate content using the in-app Report feature available on
        every companion profile and in chat.
      </p>

      <h2>7. Intellectual Property</h2>
      <p>
        The Chooze app, its design, AI models, and generated content are the intellectual
        property of Chooze. You may not reproduce, distribute, or create derivative works
        without our written permission.
      </p>

      <h2>8. Privacy</h2>
      <p>
        Your privacy is important to us. Please review our{' '}
        <a href="/privacy">Privacy Policy</a> for details on how we collect, use, and
        protect your data.
      </p>

      <h2>9. Disclaimer of Warranties</h2>
      <p>
        Chooze is provided &quot;as is&quot; and &quot;as available&quot; without warranties
        of any kind, express or implied. We do not guarantee:
      </p>
      <ul>
        <li>Uninterrupted or error-free service</li>
        <li>Accuracy or reliability of AI-generated content</li>
        <li>That the service will meet your specific requirements</li>
      </ul>

      <h2>10. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by applicable law, Chooze shall not be liable for
        any indirect, incidental, special, consequential, or punitive damages arising from
        your use of the service.
      </p>

      <h2>11. Account Termination</h2>
      <p>
        You may delete your account at any time from Settings &gt; Delete Account in the
        app, or via our <a href="/delete-account">account deletion page</a>. We may also
        terminate or suspend accounts that violate these terms.
      </p>

      <h2>12. Changes to These Terms</h2>
      <p>
        We may update these Terms of Service from time to time. Changes will be posted on
        this page. Continued use of the app after changes constitutes acceptance.
      </p>

      <h2>13. Governing Law</h2>
      <p>
        These Terms are governed by the laws of India. Any disputes arising from these
        terms shall be subject to the exclusive jurisdiction of the courts in India.
      </p>

      <h2>14. Contact Us</h2>
      <p>For questions about these terms:</p>
      <ul>
        <li>Email: <a href="mailto:support@chooze.online">support@chooze.online</a></li>
      </ul>
    </LegalPage>
  );
}
